version: '3.8'

services:
  backend:
    image: backend-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    stop_signal: SIGINT
    command: ["python", "backend.py"]
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  test:
    image: test-image
    build:
      context: ./tests
      dockerfile: Dockerfile
    command: sh -c "sleep 5 && behave --junit --junit-directory /root/_output/reports"
    depends_on:
      - backend
      - mongo
    volumes:
      - ./tests/_output:/root/_output

  unit-test:
    image: unit-test-image
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 5 && "pytest --junitxml=/root/_output/reports/junit-crud.xml --color=yes /root/endpoints_tests"
    depends_on:
      - backend
      - mongo
    volumes:
      - ./tests/_output:/root/_output