version: '3.8'

services:
  api:
    image: api-test-image
    build:
      context: .
      dockerfile: Dockerfile
    command: ["pytest", "--junitxml=/root/_output/reports/junit-apis.xml", "--color=yes", "/root/test.py"]
    volumes:
      - ./_output:/root/_output
