name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  api:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build apis
      run: make build-apis

    - name: Run apis
      run: make run-apis

    - name: clean apis
      run: make clear-apis

  crud:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build crud
      run: make build-crud

    - name: Run test crud
      run: make run-crud-test

    - name: Clean crud
      run: make clear-crud