name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
    checks: write
    pull-requests: write

jobs:
  api:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build apis
      run: make build-apis

    - name: Run apis
      run: make run-apis

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          **/_output/reports/*.xml

    - name: clean apis
      if: always()
      run: make clean-apis

  crud:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build crud
      run: make build-crud

    - name: Run behave dry-run
      run: make crud-tests-dry-run

    - name: Run test crud
      run: make run-crud-tests

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          **/tests/_output/reports/*.xml

    - name: Clean crud
      if: always()
      run: make clean-crud